import JSZip from 'jszip';
import { GeneratedScript } from '../types';

export const downloadAsTxt = (script: GeneratedScript) => {
  const content = `
TITLE: ${script.title}
LOGLINE: ${script.logline}

[ANALYSIS NOTE]
${script.analysisNote}

[CHARACTERS]
${script.characters}

==================================================
[SCRIPT START]
==================================================

${script.fullScript}
  `;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${script.title.replace(/\s+/g, '_')}_script.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const downloadAsZip = async (script: GeneratedScript) => {
  const zip = new JSZip();
  const folder = zip.folder("senior_drama_project");

  if (folder) {
    // 1. Main Script
    folder.file("script.txt", script.fullScript);
    
    // 2. Metadata/Analysis
    folder.file("analysis_and_characters.txt", `
TITLE: ${script.title}
LOGLINE: ${script.logline}

--- CHARACTERS ---
${script.characters}

--- PD NOTE (ANALYSIS) ---
${script.analysisNote}
    `);

    // 3. Readme
    folder.file("README.md", `# ${script.title}\n\nGenerated by Senior Storyteller AI.\nTarget Audience: 60+`);
  }

  const content = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(content);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${script.title.replace(/\s+/g, '_')}_package.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
